name: rasterizesvg
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/WietseWind/RasterizeSVG-Service.git
    build_command: npm run build
    run_command: npm run start:prod
    envs:
      - key: PORT
        scope: RUN_TIME
        type: GENERAL
        value: "8080"
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080

# Build-time environment only
build_env:
  - key: CARGO_HOME
    value: /opt/.cargo
  - key: RUSTUP_HOME
    value: /opt/.rustup
